theme = "PaperMod"
baseURL = 'https://thehomelabguide.com/'
languageCode = 'en-us'
title = 'The Homelab Guide'
pagination.PagerSize = 5
defaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

[params]
  author = "Charles Jordan"
  defaultTheme = "auto"  # light/dark mode support
  homeInfoParams = {Title = "Private Servers, Public Knowledge",Content = "Welcome to The Homelab Guide — simple, focused tutorials to help you self-host apps, secure your network, and reclaim your data."}
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true
  assets.favicon = "favicon.ico"  # replace with your own if needed
  assets.logo = "images/logo.png"  # optional

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/TheHomelabGuide"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@TheHomelabGuide"

  [[params.socialIcons]]
    name = "tiktok"
    url = "https://www.tiktok.com/@TheHomelabGuide"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/thehomelabguide"

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tutorials"
  url = "/tutorials/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4
